### ISSUE TITLE
Python 3.7

### ISSUE THREAD

**Issue by daimakram** [conda-incubator/condacolab#45]
@jezdez  can i please get python3.7 in condalab? It works working perfectly till yesterday, but now it is installing python 3.8.

**Comment by jaimergp** [comment]
That's Colab ships now. The 0.2.x release series will allow you to install _any_ Python version but I still need to do some testing before cutting the release.

You can try it if you install from `main` like this:

```
!pip install https://github.com/conda-incubator/condacolab/archive/main.tar.gz
```

**Comment by CanYing0913** [comment]
@jaimergp 
Hi I run into an issue when try this solution from previous issue #15 today:
> 
> You can try it if you install from `main` like this:
> 
> ```
> !pip install https://github.com/conda-incubator/condacolab/archive/main.tar.gz
> ```
Previously without Python3.8 support in `condacolab`, I used code below to install Python 3.10:
```Python
!pip install -q https://github.com/conda-incubator/condacolab/archive/main.tar.gz
import condacolab
condacolab.install_from_url("https://github.com/conda-forge/miniforge/\
releases/download/4.14.0-0/Mambaforge-4.14.0-0-Linux-x86_64.sh")
```
After I run the code above, it takes 2 minutes to finish installation, and the Colab runtime crashes. Normally it should restart in a few seconds, but now it seems it takes forever to restart the runtime.

As I mentioned in #44 , previously it doesn't work with `condacolab` default install because `condacolab` uses Python=3.7 which will cause a conflict with `mamba` pinned Python=3.8 on Colab runtime. Now simply running:
```Python
!pip install condacolab
import condacolab
condacolab.install()
```
can work with mamba with pinned Python=3.8. Just want to let you know it doesn't seem to support installing any Python version.

**Comment by jaimergp** [comment]
Yes, we released a 0.1.x hotfix to address the 3.8 issue, but the new 0.2.x series from `main` is not out yet, sorry!

Can you provide logs for the crash? They are available under the menu `Runtime > View Runtime Logs`.

**Comment by CanYing0913** [comment]
@jaimergp 
> Can you provide logs for the crash? They are available under the menu `Runtime > View Runtime Logs`.

Please ignore some warnings on notebook version (I am using 25GM RAM notebook) but is this an issue?
```
Timestamp,Level,Message
"Dec 20, 2022, 9:10:03 AM",WARNING,: No such file or directory
"Dec 20, 2022, 9:10:03 AM",WARNING,cannot stat '/usr/bin/lsb_release'
"Dec 20, 2022, 9:10:03 AM",WARNING,mv: 
"Dec 20, 2022, 9:10:03 AM",WARNING,WARNING:root:kernel 73dcfa74-b38e-4c31-bd88-0a0b355995ce restarted
"Dec 20, 2022, 9:10:03 AM",INFO,"KernelRestarter: restarting kernel (4/5), keep random ports"
"Dec 20, 2022, 9:10:01 AM",WARNING,AttributeError: module 'IPython.utils.traitlets' has no attribute 'Unicode'
"Dec 20, 2022, 9:10:01 AM",WARNING,    format_type = _traitlets.Unicode(_JAVASCRIPT_MODULE_MIME_TYPE)
"Dec 20, 2022, 9:10:01 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/google/colab/data_table.py"", line 167, in _JavascriptModuleFormatter"
"Dec 20, 2022, 9:10:01 AM",WARNING,    class _JavascriptModuleFormatter(_IPython.core.formatters.BaseFormatter):
"Dec 20, 2022, 9:10:01 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/google/colab/data_table.py"", line 166, in <module>"
"Dec 20, 2022, 9:10:01 AM",WARNING,    from google.colab import data_table
"Dec 20, 2022, 9:10:01 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/google/colab/__init__.py"", line 26, in <module>"
"Dec 20, 2022, 9:10:01 AM",WARNING,"    module = __import__(package, fromlist=[obj])"
"Dec 20, 2022, 9:10:01 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/utils/importstring.py"", line 30, in import_item"
"Dec 20, 2022, 9:10:01 AM",WARNING,    return import_item(string)
"Dec 20, 2022, 9:10:01 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/traitlets.py"", line 1989, in _resolve_string"
"Dec 20, 2022, 9:10:01 AM",WARNING,    value = self._resolve_string(value)
"Dec 20, 2022, 9:10:01 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/traitlets.py"", line 2043, in validate"
"Dec 20, 2022, 9:10:01 AM",WARNING,"    value = self.validate(obj, value)"
"Dec 20, 2022, 9:10:01 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/traitlets.py"", line 738, in _validate"
"Dec 20, 2022, 9:10:01 AM",WARNING,"    new_value = self._validate(obj, value)"
"Dec 20, 2022, 9:10:01 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/traitlets.py"", line 706, in set"
"Dec 20, 2022, 9:10:01 AM",WARNING,"    self.set(obj, value)"
"Dec 20, 2022, 9:10:01 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/traitlets.py"", line 732, in __set__"
"Dec 20, 2022, 9:10:01 AM",WARNING,"    setattr(self, name, deepcopy(config_value))"
"Dec 20, 2022, 9:10:01 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/config/configurable.py"", line 181, in _load_config"
"Dec 20, 2022, 9:10:01 AM",WARNING,    self._load_config(config)
"Dec 20, 2022, 9:10:01 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/config/configurable.py"", line 230, in update_config"
"Dec 20, 2022, 9:10:01 AM",WARNING,    self.update_config(new_config)
"Dec 20, 2022, 9:10:01 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/config/application.py"", line 961, in load_config_file"
"Dec 20, 2022, 9:10:01 AM",WARNING,"    return method(app, *args, **kwargs)"
"Dec 20, 2022, 9:10:01 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/config/application.py"", line 113, in inner"
"Dec 20, 2022, 9:10:01 AM",WARNING,    Application.load_config_file(
"Dec 20, 2022, 9:10:01 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/application.py"", line 316, in load_config_file"
"Dec 20, 2022, 9:10:01 AM",WARNING,    self.load_config_file()
"Dec 20, 2022, 9:10:01 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/application.py"", line 460, in initialize"
"Dec 20, 2022, 9:10:01 AM",WARNING,"    return method(app, *args, **kwargs)"
"Dec 20, 2022, 9:10:01 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/config/application.py"", line 113, in inner"
"Dec 20, 2022, 9:10:01 AM",WARNING,"    super(IPKernelApp, self).initialize(argv)"
"Dec 20, 2022, 9:10:01 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/ipykernel/kernelapp.py"", line 559, in initialize"
"Dec 20, 2022, 9:10:01 AM",WARNING,"    return method(app, *args, **kwargs)"
"Dec 20, 2022, 9:10:01 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/config/application.py"", line 113, in inner"
"Dec 20, 2022, 9:10:01 AM",WARNING,    app.initialize(argv)
"Dec 20, 2022, 9:10:01 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/config/application.py"", line 1040, in launch_instance"
"Dec 20, 2022, 9:10:01 AM",WARNING,    app.launch_new_instance()
"Dec 20, 2022, 9:10:01 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/ipykernel_launcher.py"", line 16, in <module>"
"Dec 20, 2022, 9:10:01 AM",WARNING,"    exec(code, run_globals)"
"Dec 20, 2022, 9:10:01 AM",WARNING,"  File ""/opt/conda/lib/python3.10/runpy.py"", line 86, in _run_code"
"Dec 20, 2022, 9:10:01 AM",WARNING,"    return _run_code(code, main_globals, None,"
"Dec 20, 2022, 9:10:01 AM",WARNING,"  File ""/opt/conda/lib/python3.10/runpy.py"", line 196, in _run_module_as_main"
"Dec 20, 2022, 9:10:01 AM",WARNING,Traceback (most recent call last):
"Dec 20, 2022, 9:10:01 AM",WARNING,  from IPython.utils import traitlets as _traitlets
"Dec 20, 2022, 9:10:01 AM",WARNING,/opt/conda/lib/python3.10/site-packages/google/colab/data_table.py:30: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
"Dec 20, 2022, 9:10:00 AM",WARNING,: No such file or directory
"Dec 20, 2022, 9:10:00 AM",WARNING,cannot stat '/usr/bin/lsb_release'
"Dec 20, 2022, 9:10:00 AM",WARNING,mv: 
"Dec 20, 2022, 9:10:00 AM",WARNING,WARNING:root:kernel 73dcfa74-b38e-4c31-bd88-0a0b355995ce restarted
"Dec 20, 2022, 9:10:00 AM",INFO,"KernelRestarter: restarting kernel (3/5), keep random ports"
"Dec 20, 2022, 9:09:58 AM",WARNING,AttributeError: module 'IPython.utils.traitlets' has no attribute 'Unicode'
"Dec 20, 2022, 9:09:58 AM",WARNING,    format_type = _traitlets.Unicode(_JAVASCRIPT_MODULE_MIME_TYPE)
"Dec 20, 2022, 9:09:58 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/google/colab/data_table.py"", line 167, in _JavascriptModuleFormatter"
"Dec 20, 2022, 9:09:58 AM",WARNING,    class _JavascriptModuleFormatter(_IPython.core.formatters.BaseFormatter):
"Dec 20, 2022, 9:09:58 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/google/colab/data_table.py"", line 166, in <module>"
"Dec 20, 2022, 9:09:58 AM",WARNING,    from google.colab import data_table
"Dec 20, 2022, 9:09:58 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/google/colab/__init__.py"", line 26, in <module>"
"Dec 20, 2022, 9:09:58 AM",WARNING,"    module = __import__(package, fromlist=[obj])"
"Dec 20, 2022, 9:09:58 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/utils/importstring.py"", line 30, in import_item"
"Dec 20, 2022, 9:09:58 AM",WARNING,    return import_item(string)
"Dec 20, 2022, 9:09:58 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/traitlets.py"", line 1989, in _resolve_string"
"Dec 20, 2022, 9:09:58 AM",WARNING,    value = self._resolve_string(value)
"Dec 20, 2022, 9:09:58 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/traitlets.py"", line 2043, in validate"
"Dec 20, 2022, 9:09:58 AM",WARNING,"    value = self.validate(obj, value)"
"Dec 20, 2022, 9:09:58 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/traitlets.py"", line 738, in _validate"
"Dec 20, 2022, 9:09:58 AM",WARNING,"    new_value = self._validate(obj, value)"
"Dec 20, 2022, 9:09:58 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/traitlets.py"", line 706, in set"
"Dec 20, 2022, 9:09:58 AM",WARNING,"    self.set(obj, value)"
"Dec 20, 2022, 9:09:58 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/traitlets.py"", line 732, in __set__"
"Dec 20, 2022, 9:09:58 AM",WARNING,"    setattr(self, name, deepcopy(config_value))"
"Dec 20, 2022, 9:09:58 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/config/configurable.py"", line 181, in _load_config"
"Dec 20, 2022, 9:09:58 AM",WARNING,    self._load_config(config)
"Dec 20, 2022, 9:09:58 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/config/configurable.py"", line 230, in update_config"
"Dec 20, 2022, 9:09:58 AM",WARNING,    self.update_config(new_config)
"Dec 20, 2022, 9:09:58 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/config/application.py"", line 961, in load_config_file"
"Dec 20, 2022, 9:09:58 AM",WARNING,"    return method(app, *args, **kwargs)"
"Dec 20, 2022, 9:09:58 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/config/application.py"", line 113, in inner"
"Dec 20, 2022, 9:09:58 AM",WARNING,    Application.load_config_file(
"Dec 20, 2022, 9:09:58 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/application.py"", line 316, in load_config_file"
"Dec 20, 2022, 9:09:58 AM",WARNING,    self.load_config_file()
"Dec 20, 2022, 9:09:58 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/application.py"", line 460, in initialize"
"Dec 20, 2022, 9:09:58 AM",WARNING,"    return method(app, *args, **kwargs)"
"Dec 20, 2022, 9:09:58 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/config/application.py"", line 113, in inner"
"Dec 20, 2022, 9:09:58 AM",WARNING,"    super(IPKernelApp, self).initialize(argv)"
"Dec 20, 2022, 9:09:58 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/ipykernel/kernelapp.py"", line 559, in initialize"
"Dec 20, 2022, 9:09:58 AM",WARNING,"    return method(app, *args, **kwargs)"
"Dec 20, 2022, 9:09:58 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/config/application.py"", line 113, in inner"
"Dec 20, 2022, 9:09:58 AM",WARNING,    app.initialize(argv)
"Dec 20, 2022, 9:09:58 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/config/application.py"", line 1040, in launch_instance"
"Dec 20, 2022, 9:09:58 AM",WARNING,    app.launch_new_instance()
"Dec 20, 2022, 9:09:58 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/ipykernel_launcher.py"", line 16, in <module>"
"Dec 20, 2022, 9:09:58 AM",WARNING,"    exec(code, run_globals)"
"Dec 20, 2022, 9:09:58 AM",WARNING,"  File ""/opt/conda/lib/python3.10/runpy.py"", line 86, in _run_code"
"Dec 20, 2022, 9:09:58 AM",WARNING,"    return _run_code(code, main_globals, None,"
"Dec 20, 2022, 9:09:58 AM",WARNING,"  File ""/opt/conda/lib/python3.10/runpy.py"", line 196, in _run_module_as_main"
"Dec 20, 2022, 9:09:58 AM",WARNING,Traceback (most recent call last):
"Dec 20, 2022, 9:09:58 AM",WARNING,  from IPython.utils import traitlets as _traitlets
"Dec 20, 2022, 9:09:58 AM",WARNING,/opt/conda/lib/python3.10/site-packages/google/colab/data_table.py:30: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
"Dec 20, 2022, 9:09:57 AM",WARNING,mv: cannot stat '/usr/bin/lsb_release': No such file or directory
"Dec 20, 2022, 9:09:57 AM",WARNING,WARNING:root:kernel 73dcfa74-b38e-4c31-bd88-0a0b355995ce restarted
"Dec 20, 2022, 9:09:57 AM",INFO,"KernelRestarter: restarting kernel (2/5), keep random ports"
"Dec 20, 2022, 9:09:55 AM",WARNING,AttributeError: module 'IPython.utils.traitlets' has no attribute 'Unicode'
"Dec 20, 2022, 9:09:55 AM",WARNING,    format_type = _traitlets.Unicode(_JAVASCRIPT_MODULE_MIME_TYPE)
"Dec 20, 2022, 9:09:55 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/google/colab/data_table.py"", line 167, in _JavascriptModuleFormatter"
"Dec 20, 2022, 9:09:55 AM",WARNING,    class _JavascriptModuleFormatter(_IPython.core.formatters.BaseFormatter):
"Dec 20, 2022, 9:09:55 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/google/colab/data_table.py"", line 166, in <module>"
"Dec 20, 2022, 9:09:55 AM",WARNING,    from google.colab import data_table
"Dec 20, 2022, 9:09:55 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/google/colab/__init__.py"", line 26, in <module>"
"Dec 20, 2022, 9:09:55 AM",WARNING,"    module = __import__(package, fromlist=[obj])"
"Dec 20, 2022, 9:09:55 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/utils/importstring.py"", line 30, in import_item"
"Dec 20, 2022, 9:09:55 AM",WARNING,    return import_item(string)
"Dec 20, 2022, 9:09:55 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/traitlets.py"", line 1989, in _resolve_string"
"Dec 20, 2022, 9:09:55 AM",WARNING,    value = self._resolve_string(value)
"Dec 20, 2022, 9:09:55 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/traitlets.py"", line 2043, in validate"
"Dec 20, 2022, 9:09:55 AM",WARNING,"    value = self.validate(obj, value)"
"Dec 20, 2022, 9:09:55 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/traitlets.py"", line 738, in _validate"
"Dec 20, 2022, 9:09:55 AM",WARNING,"    new_value = self._validate(obj, value)"
"Dec 20, 2022, 9:09:55 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/traitlets.py"", line 706, in set"
"Dec 20, 2022, 9:09:55 AM",WARNING,"    self.set(obj, value)"
"Dec 20, 2022, 9:09:55 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/traitlets.py"", line 732, in __set__"
"Dec 20, 2022, 9:09:55 AM",WARNING,"    setattr(self, name, deepcopy(config_value))"
"Dec 20, 2022, 9:09:55 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/config/configurable.py"", line 181, in _load_config"
"Dec 20, 2022, 9:09:55 AM",WARNING,    self._load_config(config)
"Dec 20, 2022, 9:09:55 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/config/configurable.py"", line 230, in update_config"
"Dec 20, 2022, 9:09:55 AM",WARNING,    self.update_config(new_config)
"Dec 20, 2022, 9:09:55 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/config/application.py"", line 961, in load_config_file"
"Dec 20, 2022, 9:09:55 AM",WARNING,"    return method(app, *args, **kwargs)"
"Dec 20, 2022, 9:09:55 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/config/application.py"", line 113, in inner"
"Dec 20, 2022, 9:09:55 AM",WARNING,    Application.load_config_file(
"Dec 20, 2022, 9:09:55 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/application.py"", line 316, in load_config_file"
"Dec 20, 2022, 9:09:55 AM",WARNING,    self.load_config_file()
"Dec 20, 2022, 9:09:55 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/application.py"", line 460, in initialize"
"Dec 20, 2022, 9:09:55 AM",WARNING,"    return method(app, *args, **kwargs)"
"Dec 20, 2022, 9:09:55 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/config/application.py"", line 113, in inner"
"Dec 20, 2022, 9:09:55 AM",WARNING,"    super(IPKernelApp, self).initialize(argv)"
"Dec 20, 2022, 9:09:55 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/ipykernel/kernelapp.py"", line 559, in initialize"
"Dec 20, 2022, 9:09:55 AM",WARNING,"    return method(app, *args, **kwargs)"
"Dec 20, 2022, 9:09:55 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/config/application.py"", line 113, in inner"
"Dec 20, 2022, 9:09:55 AM",WARNING,    app.initialize(argv)
"Dec 20, 2022, 9:09:55 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/traitlets/config/application.py"", line 1040, in launch_instance"
"Dec 20, 2022, 9:09:55 AM",WARNING,    app.launch_new_instance()
"Dec 20, 2022, 9:09:55 AM",WARNING,"  File ""/opt/conda/lib/python3.10/site-packages/ipykernel_launcher.py"", line 16, in <module>"
"Dec 20, 2022, 9:09:55 AM",WARNING,"    exec(code, run_globals)"
"Dec 20, 2022, 9:09:55 AM",WARNING,"  File ""/opt/conda/lib/python3.10/runpy.py"", line 86, in _run_code"
"Dec 20, 2022, 9:09:55 AM",WARNING,"    return _run_code(code, main_globals, None,"
"Dec 20, 2022, 9:09:55 AM",WARNING,"  File ""/opt/conda/lib/python3.10/runpy.py"", line 196, in _run_module_as_main"
"Dec 20, 2022, 9:09:55 AM",WARNING,Traceback (most recent call last):
"Dec 20, 2022, 9:09:54 AM",WARNING,  from IPython.utils import traitlets as _traitlets
"Dec 20, 2022, 9:09:54 AM",WARNING,/opt/conda/lib/python3.10/site-packages/google/colab/data_table.py:30: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
"Dec 20, 2022, 9:09:54 AM",WARNING,: No such file or directory
"Dec 20, 2022, 9:09:54 AM",WARNING,mv: cannot stat '/usr/bin/lsb_release'
"Dec 20, 2022, 9:09:54 AM",WARNING,WARNING:root:kernel 73dcfa74-b38e-4c31-bd88-0a0b355995ce restarted
"Dec 20, 2022, 9:09:54 AM",INFO,"KernelRestarter: restarting kernel (1/5), keep random ports"
"Dec 20, 2022, 9:08:24 AM",INFO,Kernel started: 73dcfa74-b38e-4c31-bd88-0a0b355995ce
"Dec 20, 2022, 9:01:51 AM",INFO,Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
"Dec 20, 2022, 9:01:51 AM",INFO,Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
"Dec 20, 2022, 9:01:51 AM",INFO,http://172.28.0.2:9000/
"Dec 20, 2022, 9:01:51 AM",INFO,http://172.28.0.12:9000/
"Dec 20, 2022, 9:01:51 AM",INFO,The Jupyter Notebook is running at:
"Dec 20, 2022, 9:01:51 AM",INFO,The Jupyter Notebook is running at:
"Dec 20, 2022, 9:01:51 AM",INFO,Serving notebooks from local directory: /
"Dec 20, 2022, 9:01:51 AM",INFO,Serving notebooks from local directory: /
"Dec 20, 2022, 9:01:51 AM",INFO,google.colab serverextension initialized.
"Dec 20, 2022, 9:01:51 AM",INFO,google.colab serverextension initialized.
"Dec 20, 2022, 9:01:51 AM",WARNING,    	/root/.jupyter/jupyter_notebook_config.json
"Dec 20, 2022, 9:01:51 AM",WARNING,    	/root/.local/etc/jupyter/jupyter_notebook_config.json
"Dec 20, 2022, 9:01:51 AM",WARNING,    	/usr/etc/jupyter/jupyter_notebook_config.json
"Dec 20, 2022, 9:01:51 AM",WARNING,    	/root/.jupyter/jupyter_notebook_config.json
"Dec 20, 2022, 9:01:51 AM",WARNING,    	/root/.local/etc/jupyter/jupyter_notebook_config.json
"Dec 20, 2022, 9:01:51 AM",WARNING,    	/usr/etc/jupyter/jupyter_notebook_config.json
"Dec 20, 2022, 9:01:51 AM",WARNING,    	/usr/local/etc/jupyter/jupyter_notebook_config.json
"Dec 20, 2022, 9:01:51 AM",WARNING,    	/usr/local/etc/jupyter/jupyter_notebook_config.d/panel-client-jupyter.json
"Dec 20, 2022, 9:01:51 AM",WARNING,    	/usr/local/etc/jupyter/jupyter_notebook_config.json
"Dec 20, 2022, 9:01:51 AM",WARNING,    	/usr/local/etc/jupyter/jupyter_notebook_config.d/panel-client-jupyter.json
"Dec 20, 2022, 9:01:51 AM",WARNING,    	/etc/jupyter/jupyter_notebook_config.json
"Dec 20, 2022, 9:01:51 AM",WARNING,    	/etc/jupyter/jupyter_notebook_config.json
"Dec 20, 2022, 9:01:51 AM",INFO,Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
"Dec 20, 2022, 9:01:51 AM",INFO,Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
"Dec 20, 2022, 9:01:51 AM",WARNING,Notebook version 5 is no longer maintained. Please upgrade to version 6 or later.
"Dec 20, 2022, 9:01:51 AM",WARNING,Notebook version 5 is no longer maintained. Please upgrade to version 6 or later.
```

**Comment by jaimergp** [comment]
I see two errors:

```
"Dec 20, 2022, 9:10:03 AM",WARNING,cannot stat '/usr/bin/lsb_release'
```

and:

```
"Dec 20, 2022, 9:09:55 AM",WARNING,AttributeError: module 'IPython.utils.traitlets' has no attribute 'Unicode'
```

, which leads me to think there have been API changes in ipython.

Both can be fixed but the 2nd will need some extra debugging work and I am bit short of bandwidth these weeks 😬  I'll try to see if I can work on it next week, but most probably it will be somewhere in January.

Thanks for the report!

**Comment by jaimergp** [comment]
0.2.x is now ready for testing. Check details at https://github.com/conda-incubator/condacolab/issues/34#issuecomment-5279663928 and reply there, thanks!
